import json

# Example reference table (expand as needed)
REFERENCE_NUTRITION = {
    "salmon": {"calories": 177, "protein": 17.4, "fat": 10.5, "carbohydrates": 0},
    "chicken breast": {"calories": 165, "protein": 31, "fat": 3.6, "carbohydrates": 0},
    "egg": {"calories": 68, "protein": 5.5, "fat": 4.8, "carbohydrates": 0.6},
    "apple": {"calories": 95, "protein": 0.5, "fat": 0.3, "carbohydrates": 25},
    "banana": {"calories": 105, "protein": 1.3, "fat": 0.4, "carbohydrates": 27},
    "broccoli": {"calories": 31, "protein": 2.5, "fat": 0.3, "carbohydrates": 6},
    "carrot": {"calories": 25, "protein": 0.6, "fat": 0.1, "carbohydrates": 6},
    "potato": {"calories": 163, "protein": 4.3, "fat": 0.2, "carbohydrates": 37},
    "rice": {"calories": 205, "protein": 4.3, "fat": 0.4, "carbohydrates": 45},
    "olive oil": {"calories": 119, "protein": 0, "fat": 13.5, "carbohydrates": 0},
    "almonds": {"calories": 164, "protein": 6, "fat": 14, "carbohydrates": 6},
    "spinach": {"calories": 7, "protein": 0.9, "fat": 0.1, "carbohydrates": 1.1},
    "cheddar cheese": {"calories": 113, "protein": 7, "fat": 9, "carbohydrates": 0.4},
    "milk": {"calories": 103, "protein": 8, "fat": 2.4, "carbohydrates": 12},
    "yogurt": {"calories": 59, "protein": 10, "fat": 0.4, "carbohydrates": 3.6},
    "black pepper": {"calories": 6, "protein": 0.0, "fat": 0.0, "carbohydrates": 0.9},
    "cumin": {"calories": 8, "protein": 0.4, "fat": 0.5, "carbohydrates": 0.7},
    "paprika": {"calories": 6, "protein": 0.3, "fat": 0.3, "carbohydrates": 0.6},
    "chili powder": {"calories": 8, "protein": 0.4, "fat": 0.4, "carbohydrates": 0.7},
    "garlic powder": {"calories": 10, "protein": 0.5, "fat": 0.0, "carbohydrates": 2.2},
    "onion powder": {"calories": 8, "protein": 0.2, "fat": 0.0, "carbohydrates": 1.6},
    "cinnamon": {"calories": 6, "protein": 0.1, "fat": 0.0, "carbohydrates": 0.7},
    "nutmeg": {"calories": 12, "protein": 0.1, "fat": 0.8, "carbohydrates": 0.6},
    "cloves": {"calories": 6, "protein": 0.1, "fat": 0.3, "carbohydrates": 0.7},
    "coriander": {"calories": 5, "protein": 0.2, "fat": 0.1, "carbohydrates": 0.3},
    "thyme": {"calories": 3, "protein": 0.1, "fat": 0.1, "carbohydrates": 0.2},
    "basil": {"calories": 1, "protein": 0.1, "fat": 0.0, "carbohydrates": 0.1},
    "oregano": {"calories": 3, "protein": 0.1, "fat": 0.1, "carbohydrates": 0.3},
    "garlic": {"calories": 10, "protein": 0.5, "fat": 0.0, "carbohydrates": 2.2},
    "avocado": {"calories": 240, "protein": 3, "fat": 22, "carbohydrates": 12},
    "beef": {"calories": 250, "protein": 26, "fat": 17, "carbohydrates": 0},
    "butter": {"calories": 102, "protein": 0.1, "fat": 11.5, "carbohydrates": 0},
    "beans": {"calories": 127, "protein": 8.7, "fat": 0.5, "carbohydrates": 23},
    "cod": {"calories": 89, "protein": 19.4, "fat": 0.7, "carbohydrates": 0},
    "cottage cheese": {"calories": 98, "protein": 11, "fat": 4.3, "carbohydrates": 3.4},
    "egg whites": {"calories": 17, "protein": 3.6, "fat": 0.1, "carbohydrates": 0.2},
    "egg yolks": {"calories": 55, "protein": 2.7, "fat": 4.5, "carbohydrates": 0.6},
    "flax seeds": {"calories": 55, "protein": 1.9, "fat": 4.3, "carbohydrates": 3},
    "honey": {"calories": 64, "protein": 0.1, "fat": 0, "carbohydrates": 17},
    "kale": {"calories": 33, "protein": 2.9, "fat": 0.6, "carbohydrates": 6},
    "lentils": {"calories": 230, "protein": 18, "fat": 0.8, "carbohydrates": 40},
    "mayonnaise": {"calories": 94, "protein": 0.1, "fat": 10, "carbohydrates": 0.1},
    "mozzarella cheese": {"calories": 85, "protein": 6.3, "fat": 6.3, "carbohydrates": 0.6},
    "oats": {"calories": 150, "protein": 5, "fat": 2.5, "carbohydrates": 27},
    "onion": {"calories": 44, "protein": 1.2, "fat": 0.1, "carbohydrates": 10},
    "peanut butter": {"calories": 188, "protein": 8, "fat": 16, "carbohydrates": 6},
    "quinoa": {"calories": 222, "protein": 8, "fat": 3.6, "carbohydrates": 39},
    "shrimp": {"calories": 84, "protein": 18, "fat": 0.2, "carbohydrates": 0.2},
    "sweet potatoes": {"calories": 112, "protein": 2, "fat": 0.1, "carbohydrates": 26},
    "tofu": {"calories": 76, "protein": 8, "fat": 4.8, "carbohydrates": 1.9},
    "tomato": {"calories": 22, "protein": 1.1, "fat": 0.2, "carbohydrates": 4.8},
    "walnuts": {"calories": 185, "protein": 4.3, "fat": 18.5, "carbohydrates": 3.9},
    "zucchini": {"calories": 33, "protein": 2.4, "fat": 0.6, "carbohydrates": 6.1},
    "all purpose flour": {"calories": 102, "protein": 3, "fat": 0.3, "carbohydrates": 22},
    "almond butter": {"calories": 196, "protein": 7, "fat": 18, "carbohydrates": 6},
    "almond flour": {"calories": 160, "protein": 6, "fat": 14, "carbohydrates": 6},
    "almond milk": {"calories": 30, "protein": 1, "fat": 2.5, "carbohydrates": 1},
    "baking powder": {"calories": 2, "protein": 0, "fat": 0, "carbohydrates": 1},
    "baking soda": {"calories": 0, "protein": 0, "fat": 0, "carbohydrates": 0},
    "balsamic vinegar": {"calories": 14, "protein": 0, "fat": 0, "carbohydrates": 3},
    "beef broth": {"calories": 10, "protein": 1, "fat": 0, "carbohydrates": 1},
    "breadcrumbs": {"calories": 110, "protein": 4, "fat": 1.5, "carbohydrates": 20},
    "cashews": {"calories": 157, "protein": 5, "fat": 12, "carbohydrates": 9},
    "cauliflower": {"calories": 25, "protein": 1.9, "fat": 0.3, "carbohydrates": 5},
    "coconut oil": {"calories": 121, "protein": 0, "fat": 13.5, "carbohydrates": 0},
    "cream cheese": {"calories": 99, "protein": 2, "fat": 10, "carbohydrates": 2},
    "dijon mustard": {"calories": 5, "protein": 0, "fat": 0, "carbohydrates": 0},
    "feta cheese": {"calories": 75, "protein": 4, "fat": 6, "carbohydrates": 1.1},
    "ginger": {"calories": 5, "protein": 0.1, "fat": 0, "carbohydrates": 1},
    "ketchup": {"calories": 20, "protein": 0, "fat": 0, "carbohydrates": 5},
    "lemon juice": {"calories": 3, "protein": 0, "fat": 0, "carbohydrates": 1},
    "maple syrup": {"calories": 52, "protein": 0, "fat": 0, "carbohydrates": 13},
    "parmesan cheese": {"calories": 22, "protein": 2, "fat": 1.5, "carbohydrates": 0.2},
    "soy sauce": {"calories": 10, "protein": 1, "fat": 0, "carbohydrates": 1},
    "sugar": {"calories": 16, "protein": 0, "fat": 0, "carbohydrates": 4},
    "tuna": {"calories": 132, "protein": 28, "fat": 1, "carbohydrates": 0},
    "vanilla extract": {"calories": 12, "protein": 0, "fat": 0, "carbohydrates": 0.5},
    "vinegar": {"calories": 3, "protein": 0, "fat": 0, "carbohydrates": 0.1},
    "worcestershire sauce": {"calories": 5, "protein": 0, "fat": 0, "carbohydrates": 1},
    "artichoke hearts": {"calories": 60, "protein": 3, "fat": 0, "carbohydrates": 13},
    "arugula": {"calories": 5, "protein": 0.5, "fat": 0.1, "carbohydrates": 0.7},
    "asparagus": {"calories": 20, "protein": 2.2, "fat": 0.1, "carbohydrates": 3.9},
    "bacon": {"calories": 43, "protein": 3, "fat": 3.3, "carbohydrates": 0.1},
    "bell peppers": {"calories": 24, "protein": 0.9, "fat": 0.2, "carbohydrates": 6},
    "black beans": {"calories": 227, "protein": 15, "fat": 0.9, "carbohydrates": 41},
    "blue cheese": {"calories": 100, "protein": 6, "fat": 8, "carbohydrates": 1},
    "cabbage": {"calories": 22, "protein": 1.3, "fat": 0.1, "carbohydrates": 5},
    "capers": {"calories": 5, "protein": 0.2, "fat": 0.1, "carbohydrates": 1},
    "celery": {"calories": 6, "protein": 0.3, "fat": 0.1, "carbohydrates": 1.4},
    "cherries": {"calories": 50, "protein": 1, "fat": 0.3, "carbohydrates": 12},
    "chia seeds": {"calories": 138, "protein": 4.7, "fat": 8.7, "carbohydrates": 12},
    "chickpeas": {"calories": 269, "protein": 15, "fat": 4.2, "carbohydrates": 45},
    "coconut": {"calories": 354, "protein": 3.3, "fat": 33.5, "carbohydrates": 15},
    "corn": {"calories": 86, "protein": 3.2, "fat": 1.2, "carbohydrates": 19},
    "cranberries": {"calories": 46, "protein": 0.4, "fat": 0.1, "carbohydrates": 12},
    "cucumber": {"calories": 8, "protein": 0.3, "fat": 0.1, "carbohydrates": 1.9},
    "dates": {"calories": 282, "protein": 2.5, "fat": 0.4, "carbohydrates": 75},
    "eggplant": {"calories": 25, "protein": 1, "fat": 0.2, "carbohydrates": 6},
    "figs": {"calories": 74, "protein": 0.8, "fat": 0.3, "carbohydrates": 19},
    "flour": {"calories": 455, "protein": 10, "fat": 1, "carbohydrates": 95},
    "green beans": {"calories": 31, "protein": 1.8, "fat": 0.1, "carbohydrates": 7},
    "ham": {"calories": 145, "protein": 21, "fat": 6, "carbohydrates": 1.5},
    "heavy cream": {"calories": 51, "protein": 0.3, "fat": 5.4, "carbohydrates": 0.4},
    "jalapeno": {"calories": 4, "protein": 0.1, "fat": 0.1, "carbohydrates": 0.9},
    "leeks": {"calories": 61, "protein": 1.5, "fat": 0.3, "carbohydrates": 14},
    "lettuce": {"calories": 5, "protein": 0.5, "fat": 0.1, "carbohydrates": 1},
    "lime": {"calories": 20, "protein": 0.5, "fat": 0.1, "carbohydrates": 7},
    "mushrooms": {"calories": 22, "protein": 3.1, "fat": 0.3, "carbohydrates": 3.3},
    "olives": {"calories": 115, "protein": 0.8, "fat": 10.7, "carbohydrates": 6},
    "orange": {"calories": 62, "protein": 1.2, "fat": 0.2, "carbohydrates": 15},
    "parsley": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.2},
    "peaches": {"calories": 59, "protein": 1.4, "fat": 0.4, "carbohydrates": 15},
    "pears": {"calories": 101, "protein": 0.6, "fat": 0.2, "carbohydrates": 27},
    "peas": {"calories": 81, "protein": 5.4, "fat": 0.4, "carbohydrates": 14},
    "pecans": {"calories": 196, "protein": 2.6, "fat": 20.4, "carbohydrates": 3.9},
    "pineapple": {"calories": 82, "protein": 0.9, "fat": 0.2, "carbohydrates": 22},
    "pistachios": {"calories": 159, "protein": 6, "fat": 13, "carbohydrates": 8},
    "plums": {"calories": 46, "protein": 0.7, "fat": 0.3, "carbohydrates": 11},
    "pork": {"calories": 242, "protein": 27, "fat": 14, "carbohydrates": 0},
    "pumpkin": {"calories": 26, "protein": 1, "fat": 0.1, "carbohydrates": 7},
    "radishes": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.2},
    "raspberries": {"calories": 64, "protein": 1.5, "fat": 0.8, "carbohydrates": 15},
    "red onion": {"calories": 40, "protein": 1.1, "fat": 0.1, "carbohydrates": 9},
    "scallops": {"calories": 88, "protein": 17, "fat": 0.8, "carbohydrates": 2.4},
    "sesame seeds": {"calories": 52, "protein": 1.6, "fat": 4.5, "carbohydrates": 2.1},
    "shallots": {"calories": 7, "protein": 0.2, "fat": 0, "carbohydrates": 1.7},
    "sour cream": {"calories": 59, "protein": 0.7, "fat": 5.8, "carbohydrates": 1.3},
    "strawberries": {"calories": 49, "protein": 1, "fat": 0.5, "carbohydrates": 12},
    "sunflower seeds": {"calories": 164, "protein": 5.8, "fat": 14, "carbohydrates": 6},
    "sweet potato": {"calories": 86, "protein": 1.6, "fat": 0.1, "carbohydrates": 20},
    "tilapia": {"calories": 96, "protein": 20, "fat": 1.7, "carbohydrates": 0},
    "turkey": {"calories": 135, "protein": 29, "fat": 1, "carbohydrates": 0},
    "watercress": {"calories": 4, "protein": 0.8, "fat": 0, "carbohydrates": 0.4},
    "watermelon": {"calories": 86, "protein": 1.7, "fat": 0.4, "carbohydrates": 21},
    "beets": {"calories": 43, "protein": 1.6, "fat": 0.2, "carbohydrates": 10},
    "black olives": {"calories": 115, "protein": 0.8, "fat": 10.7, "carbohydrates": 6.3},
    "blueberries": {"calories": 57, "protein": 0.7, "fat": 0.3, "carbohydrates": 14},
    "brandy": {"calories": 65, "protein": 0, "fat": 0, "carbohydrates": 0},
    "brussels sprouts": {"calories": 43, "protein": 3.4, "fat": 0.3, "carbohydrates": 9},
    "buckwheat": {"calories": 343, "protein": 13, "fat": 3.4, "carbohydrates": 72},
    "cashew milk": {"calories": 25, "protein": 1, "fat": 2, "carbohydrates": 1},
    "cauliflower florets": {"calories": 25, "protein": 1.9, "fat": 0.3, "carbohydrates": 5},
    "celery stick": {"calories": 6, "protein": 0.3, "fat": 0.1, "carbohydrates": 1.4},
    "cherry tomatoes": {"calories": 18, "protein": 0.9, "fat": 0.2, "carbohydrates": 3.9},
    "chicken": {"calories": 239, "protein": 27, "fat": 14, "carbohydrates": 0},
    "chicken broth": {"calories": 10, "protein": 1, "fat": 0, "carbohydrates": 1},
    "chives": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.1},
    "cilantro": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.1},
    "coconut milk": {"calories": 230, "protein": 2.3, "fat": 24, "carbohydrates": 6},
    "corn tortillas": {"calories": 218, "protein": 6, "fat": 2.5, "carbohydrates": 45},
    "dill": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.2},
    "english cucumber": {"calories": 8, "protein": 0.3, "fat": 0.1, "carbohydrates": 1.9},
    "fennel": {"calories": 31, "protein": 1.2, "fat": 0.2, "carbohydrates": 7},
    "fish sauce": {"calories": 5, "protein": 1, "fat": 0, "carbohydrates": 0},
    "flank steak": {"calories": 212, "protein": 28, "fat": 10, "carbohydrates": 0},
    "french bread": {"calories": 272, "protein": 10, "fat": 2.5, "carbohydrates": 52},
    "garlic cloves": {"calories": 5, "protein": 0.2, "fat": 0, "carbohydrates": 1},
    "ghee": {"calories": 112, "protein": 0, "fat": 13, "carbohydrates": 0},
    "greek yogurt": {"calories": 59, "protein": 10, "fat": 0.4, "carbohydrates": 3.6},
    "green bell pepper": {"calories": 20, "protein": 0.9, "fat": 0.2, "carbohydrates": 4.6},
    "green onions": {"calories": 5, "protein": 0.3, "fat": 0, "carbohydrates": 1},
    "gruyere cheese": {"calories": 117, "protein": 8.5, "fat": 9, "carbohydrates": 0.1},
    "iceberg lettuce": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.2},
    "jasmine rice": {"calories": 205, "protein": 4.3, "fat": 0.4, "carbohydrates": 45},
    "kidney beans": {"calories": 127, "protein": 8.7, "fat": 0.5, "carbohydrates": 23},
    "lamb": {"calories": 282, "protein": 25, "fat": 20, "carbohydrates": 0},
    "lemon": {"calories": 17, "protein": 0.6, "fat": 0.2, "carbohydrates": 5},
    "lime juice": {"calories": 4, "protein": 0.1, "fat": 0, "carbohydrates": 1.3},
    "mango": {"calories": 60, "protein": 0.8, "fat": 0.4, "carbohydrates": 15},
    "mint leaves": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.2},
    "mustard": {"calories": 9, "protein": 0.5, "fat": 0.5, "carbohydrates": 0.5},
    "navy beans": {"calories": 140, "protein": 8, "fat": 0.6, "carbohydrates": 26},
    "oat milk": {"calories": 120, "protein": 3, "fat": 5, "carbohydrates": 16},
    "pesto": {"calories": 80, "protein": 2, "fat": 8, "carbohydrates": 1},
    "pickles": {"calories": 0, "protein": 0, "fat": 0, "carbohydrates": 0},
    "pine nuts": {"calories": 191, "protein": 3.9, "fat": 19, "carbohydrates": 3.7},
    "pinto beans": {"calories": 143, "protein": 8, "fat": 0.5, "carbohydrates": 26},
    "pomegranate seeds": {"calories": 83, "protein": 1.7, "fat": 1.2, "carbohydrates": 19},
    "pork chops": {"calories": 221, "protein": 26, "fat": 12, "carbohydrates": 0},
    "raisins": {"calories": 299, "protein": 3.1, "fat": 0.5, "carbohydrates": 79},
    "red bell pepper": {"calories": 31, "protein": 1, "fat": 0.3, "carbohydrates": 6},
    "red wine vinegar": {"calories": 3, "protein": 0, "fat": 0, "carbohydrates": 0},
    "romaine lettuce": {"calories": 1, "protein": 0.1, "fat": 0, "carbohydrates": 0.2},
    "rosemary": {"calories": 1, "protein": 0, "fat": 0.1, "carbohydrates": 0.2},
    "salsa": {"calories": 10, "protein": 0.5, "fat": 0.1, "carbohydrates": 2},
    "sausage": {"calories": 346, "protein": 13, "fat": 31, "carbohydrates": 1.3},
    "sesame oil": {"calories": 120, "protein": 0, "fat": 14, "carbohydrates": 0},
    "sour cream": {"calories": 59, "protein": 0.7, "fat": 5.8, "carbohydrates": 1.3},
    "spaghetti": {"calories": 221, "protein": 8, "fat": 1.3, "carbohydrates": 43},
    "sriracha": {"calories": 5, "protein": 0, "fat": 0, "carbohydrates": 1},
    "swiss cheese": {"calories": 108, "protein": 8, "fat": 8, "carbohydrates": 1},
    "tahini": {"calories": 89, "protein": 2.6, "fat": 8, "carbohydrates": 3.2},
    "vegetable broth": {"calories": 15, "protein": 1, "fat": 0, "carbohydrates": 3},
    "white onion": {"calories": 40, "protein": 1.1, "fat": 0.1, "carbohydrates": 9},
    "white rice": {"calories": 205, "protein": 4.3, "fat": 0.4, "carbohydrates": 45},
    "white wine": {"calories": 82, "protein": 0.1, "fat": 0, "carbohydrates": 2.6},
    "yellow onion": {"calories": 40, "protein": 1.1, "fat": 0.1, "carbohydrates": 9},
    "whole wheat bread": {"calories": 69, "protein": 3.6, "fat": 1.1, "carbohydrates": 13},
    "wild rice": {"calories": 166, "protein": 6.5, "fat": 0.6, "carbohydrates": 35},
    "wine vinegar": {"calories": 3, "protein": 0, "fat": 0, "carbohydrates": 0.1},
    "yeast": {"calories": 20, "protein": 2.8, "fat": 0.5, "carbohydrates": 2.6},
    "yellow bell pepper": {"calories": 27, "protein": 1, "fat": 0.2, "carbohydrates": 6},
    "zucchini noodles": {"calories": 19, "protein": 1.4, "fat": 0.4, "carbohydrates": 3.5}
}

def get_reference_nutrition(ingredient):
    key = ingredient.lower().strip()
    return REFERENCE_NUTRITION.get(key, {"calories": "TBD", "protein": "TBD", "fat": "TBD", "carbohydrates": "TBD"})

if __name__ == "__main__":
    with open("foodBERT/foodbert_embeddings/data/used_ingredients_clean.json", "r", encoding="utf-8") as f:
        ingredients = json.load(f)

    enriched = []
    for ingredient in ingredients:
        nutrition = get_reference_nutrition(ingredient)
        enriched.append({
            "ingredient": ingredient,
            "nutritionix_nutrition_profile": nutrition
        })

    with open("enriched_ingredient_data_nutritionix.json", "w", encoding="utf-8") as f:
        json.dump(enriched, f, ensure_ascii=False, indent=2)

    print(f"Enriched {len(enriched)} ingredients using reference Nutritionix/public data. Output saved to enriched_ingredient_data_nutritionix.json.")
